import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * The API Reference category is autogenerated from `docs/api-reference`, which
 * `@vantagecompute/docusaurus-plugin-pydoc` writes at build time from the docstrings in
 * `armasec_lite/`. Those pages are not committed, so this sidebar is the only place the
 * reference's position in the tree is declared.
 *
 * The Benchmarks category works the same way: `scripts/generate_benchmarks.py` writes
 * `docs/benchmarks` at build time from the committed comparison results, one page per run
 * plus a summary, and those pages are not committed either. The category is autogenerated
 * because the number of runs grows every time one is committed, and a hand-maintained list
 * would go stale on exactly the commit that mattered.
 */
const sidebars: SidebarsConfig = {
  docsSidebar: [
    'index',
    {
      type: 'category',
      label: 'Getting Started',
      items: ['installation', 'quickstart', 'migration'],
    },
    {
      type: 'category',
      label: 'Architecture',
      items: [
        'architecture/index',
        'architecture/request-lifecycle',
        'architecture/caching',
        'architecture/threading-model',
      ],
    },
    {
      type: 'category',
      label: 'Security',
      link: {type: 'doc', id: 'security/index'},
      items: ['security/jwt-verification', 'security/threat-model'],
    },
    {
      type: 'category',
      label: 'Benchmarks',
      link: {type: 'doc', id: 'benchmarks/index'},
      items: [{type: 'autogenerated', dirName: 'benchmarks'}],
    },
    {
      type: 'category',
      label: 'Reference',
      items: [
        {
          type: 'category',
          label: 'API Reference',
          link: {type: 'doc', id: 'api-reference/index'},
          items: [{type: 'autogenerated', dirName: 'api-reference'}],
        },
        'contributing',
      ],
    },
  ],
};

export default sidebars;
